class Wisdom
{
	public static void main(String[]args)
	{
		String greeting = "Good Morning";	
			System.out.println("Here, is the greeting:"+greeting);	
		String nameOfTheDay="Saturday";	
			System.out.println("Today is:"+nameOfTheDay);	
		String todayIs="weekend";
			System.out.println("Guess what today is:"+todayIs);
		String guessWhat=todayIs+"!!!Let's Enjoy";	                                                                                                                                   //1
			System.out.println(guessWhat);
		String dateToday="29/06/2024";	
			System.out.println("Today date is:"+dateToday);
		String timeNow="10.30am";
			System.out.println("time now:"+timeNow);
		String dateAndTime= dateToday+timeNow;
			System.out.println(dateAndTime);                                                                                                                                   //2
		String salutation= "Hi"+greeting;
			System.out.println("Here is the wishes:"+salutation);
		String emailAddress="kannadathi@gmail.com";	
			System.out.println("here is the format of a gmail id:"+emailAddress);                                                                                                                                   //3
		String loginInfo= "if we want login to a application we need email address in the form of"+emailAddress+" and a password";	
			System.out.println(loginInfo);
		String password="kannadathi@123456";
			System.out.println("password format"+password);
		String firstName="Bhoomika";
			System.out.println("First nmae is:"+firstName);                                                                                                                                   //4
		String lastName= "Patel";	
			System.out.println("Last name is:"+lastName);
		String fullName= firstName+lastName;	
			System.out.println("full name is"+fullName);
		String cityName="Shivamogga";	
			System.out.println("Current city name is;"+cityName);                                                                                                                                   //5
		String countryName="India";	
			System.out.println("Country name is:"+countryName);
		String residentialAddress=cityName+""+countryName;
			System.out.println(residentialAddress);
		String favColor="Blue";	
			System.out.println("Favorite color is:"+favColor);
		String carModel = "Tesla"; 	
			System.out.println("Car name is:"+carModel);                                                                                                                                   //6
		String favHobby="Photography";	
			System.out.println("favorite color is:"+favHobby);
		String favoritesAre=favColor+" "+favHobby; 	
			System.out.println("Favorite color and hobby are:"+favoritesAre);
		String nationalityIs="Indian";	
			System.out.println("Nationality is:"+nationalityIs);                                                                                                                                   //7
		String passportNo="HIp234drer";	
			System.out.println("Passport number is:"+passportNo);
		String abroadTo="He/She is having number passport"+passportNo+"of "+nationalityIs+" nationality";
			System.out.println(abroadTo);
		String epicNum="XMA54122";	
			System.out.println("Voter ID number is:"+epicNum);                                                                                                                                   //8
		String citizenInfo="he/she having epic number"+epicNum+"a proof for citizen of India";	
			System.out.println(citizenInfo);
		String postalCode="577426";	
			System.out.println("my town pincode number is:"+postalCode);
		String bankName="Canara Bank";	
			System.out.println("bank:"+bankName);                                                                                                                                   //9
		String branchName="Ripponpet"; 	
			System.out.println("Bank branch name is:"+branchName);
		String accountNumber="08182237475"; 	
			System.out.println("Account number is:"+accountNumber);
		String bankInfo="He/she is having account in"+bankName+"in"+branchName+"account number is:"+accountNumber;	
			System.out.println("Bank details:"+bankInfo);                                                                                                                                   //10
		String creditCardNum="3214 5678 8654";	
			System.out.println("credit card number is:"+creditCardNum);
		String pinNumber="3456";	
			System.out.println("Credit card pin is:"+pinNumber);
		String cardDetails="credit card number is "+creditCardNum+""+"pin number is"+pinNumber;	
			System.out.println(cardDetails);                                                                                                                                   //11
		String busNumber="KA 15 NG 3245";		
			System.out.println("Bus chassie number is:"+busNumber);
		String busName ="NavaDurga";	
			System.out.println("Bus name is:"+busName);
		String busInfo="bus name is"+busNumber+"and registered as"+busNumber;	
			System.out.println(busInfo);                                                                                                                                   //12
		String deploymentDate = "2024-06-01";
			System.out.println("deployment date is"+deploymentDate);
		String scriptVersion = "1.2.3";
			System.out.println("script version is:"+scriptVersion);
		String scriptName = "dataProcessor.py";
			System.out.println("script name is:"+scriptName);                                                                                                                                   //13
		String productName = "Laptop";
			System.out.println(productName);
		String serialNumber = "SN123456789";
			System.out.println(serialNumber);
		String productDetails=productName+""+serialNumber;
			System.out.println(productDetails);
		String manufacturer = "TechCorp";
			System.out.println(manufacturer);
		String modelNumber = "X2000";
			System.out.println(modelNumber);
		String warrantyPeriod = "2 Years";
			System.out.println(warrantyPeriod);
		String manufacturerDetails=manufacturer+""+modelNumber+""+"warrantyperiod:"+warrantyPeriod;
			System.out.println(manufacturerDetails);
		String purchaseDate = "2023-01-15";
			System.out.println(purchaseDate);
		String price = "1200.99";
			System.out.println(price);
		String currency = "USD";
			System.out.println(currency);
		String finalPrice=price+""+currency;
			System.out.println(finalPrice);
		String supplierName = "ElectroMart";
			System.out.println(supplierName);
		String invoiceNumber = "INV001234";
			System.out.println(invoiceNumber);
		String paymentMethod = "Credit Card";
			System.out.println(paymentMethod);
		String deliveryDate = "2023-01-20";
			System.out.println(deliveryDate);
		String customerName = "Alice Johnson";
			System.out.println(customerName);
		String customerID = "CUST001";
			System.out.println(customerID);
		String orderNumber = "ORD12345";
		String customerDetails=customerName+"having customer Id"+customerID;
		System.out.println(customerDetails);
			System.out.println(orderNumber);
		String shippingAddress = "456 Elm St";
			System.out.println(shippingAddress);
		String billingAddress = "789 Oak St";
			System.out.println(billingAddress);
		String orderStatus = "Shipped";
			System.out.println(orderStatus);
		String addressForDelivery="His/Her address is"+shippingAddress+""+billingAddress;
			System.out.println(addressForDelivery);
		String trackingNumber = "TRACK98765";
			System.out.println(trackingNumber);
		String itemDescription = "15-inch Laptop";
			System.out.println(itemDescription);
		String itemSKU = "LAPTOP15X";
			System.out.println(itemSKU);
		String orderName= itemDescription+""+itemSKU;
			System.out.println(orderName);
		String quantityOrdered = "2";
			System.out.println(quantityOrdered);
		String quantityShipped = "2";
			System.out.println(quantityShipped);
		String shippingMethod = "Express";
			System.out.println(shippingMethod);
		String shippingDetails="quantity:"+quantityOrdered+"shipped:"+quantityShipped;
			System.out.println(shippingDetails);
		String returnPolicy = "30 Days";
			System.out.println(returnPolicy);
		String customerSupportNumber = "1-800-123-4567";
			System.out.println(customerSupportNumber);
		String supportEmail = "support@techcorp.com";
			System.out.println(supportEmail);
		String customerHelpline=customerSupportNumber+""+supportEmail;
			System.out.println(customerHelpline);
		String feedback = "Great service";
			System.out.println(feedback);
		String reviewRating = "5 Stars";
			System.out.println(reviewRating);
		String userReview=feedback+""+reviewRating;
			System.out.println(userReview);
		String promotionCode = "SAVE20";
			System.out.println(promotionCode);
		String discountAmount = "20.00";
			System.out.println(discountAmount);
		String subtotal = "2400.00";
			System.out.println(subtotal);
		String taxAmount = "192.00";
			System.out.println(taxAmount);
		String totalAmount = "2592.00";
			System.out.println(totalAmount);
		String finalAmount=subtotal+"+"+taxAmount;	
		String paymentStatus = "Paid";
			System.out.println(paymentStatus);
		String refundStatus = "Not Applicable";
			System.out.println(refundStatus);
		String transactionDetails=totalAmount+""+paymentStatus;
			System.out.println(transactionDetails);
		String shipmentCarrier = "FedEx";
			System.out.println(shipmentCarrier);
		String estimatedDelivery = "2023-01-22";
			System.out.println(estimatedDelivery);
		String orderNotes = "Leave package at the front door";
			System.out.println(orderNotes);
		String couponCode = "WELCOME10";
			System.out.println(couponCode);
		String giftCardCode = "GIFT123";
		String availableOffer=couponCode+"and"+giftCardCode;
			System.out.println(availableOffer);
			System.out.println(giftCardCode);
		String accountBalance = "500.00";
			System.out.println(accountBalance);
		String rewardPoints = "250";
			System.out.println(rewardPoints);
		String subscriptionPlan = "Monthly";
			System.out.println(subscriptionPlan);
		String subscriptionStatus = "Active";
			System.out.println(subscriptionStatus);
		String subscriptionDetail=subscriptionPlan+""+subscriptionStatus;
			System.out.println(subscriptionDetail);	
		String lastLogin = "2023-06-01 14:30:00";
			System.out.println(lastLogin);
		String accountType = "Premium";
			System.out.println(accountType);
		String membershipID = "MEM12345";
			System.out.println(membershipID);
		String loyaltyProgram = "Gold";
			System.out.println(loyaltyProgram);
		String newsletterSubscribed = "Yes";
			System.out.println(newsletterSubscribed);
		String userAccountDetails=	membershipID+"type"+loyaltyProgram;
			System.out.println(userAccountDetails);
		String preferredContactMethod = "Email";
			System.out.println(preferredContactMethod);
		String profilePictureURL = "http://example.com/profile.jpg";
			System.out.println(profilePictureURL);
		String bioDescription = "Tech enthusiast and blogger";
			System.out.println(bioDescription);
		String websiteURL = "http://bhoomipatel.com";
			System.out.println(websiteURL);
		String socialMediaHandle = "@bhoomi_patel";
			System.out.println(socialMediaHandle);
		String notificationsEnabled = "Yes";
			System.out.println(notificationsEnabled);
		String languagePreference = "English";
			System.out.println(languagePreference);
		String timezone = "GMT";
			System.out.println(timezone);
		String recentActivity = "Purchased Laptop";
			System.out.println(recentActivity);
		String favoriteCategory = "Electronics";
			System.out.println(favoriteCategory);
		String wishlistItems = "Smartphone, Tablet";
			System.out.println(wishlistItems);
		String searchHistory=favoriteCategory+"->"+wishlistItems;	
		String savedPaymentMethod = "Visa Ending 1234";
			System.out.println(savedPaymentMethod);
		String shippingPreference = "Standard";
			System.out.println(shippingPreference);
		String deliveryInstructions = "Call upon arrival";
			System.out.println(deliveryInstructions);
		String accountCreationDate = "2020-05-10";
			System.out.println(accountCreationDate);																																				//43
		String flightNumber="AB321222";	
			System.out.println("flight number is:"+flightNumber);
		String travelAgenccy="IndiGo";	
			System.out.println("Flight owner Company:"+travelAgenccy);
		String flightInfo="Flight number is"+flightNumber+"owned by"+" "+travelAgenccy;
			System.out.println(flightInfo);                                                                                                                                   //44
		String hotelName="Malnad Shire";	
			System.out.println("Restuarent name:"+hotelName);
		String roomNumber="567";
			System.out.println("Room number is:"+roomNumber);
		String hotelInfo="He/she staying in "+hotelName+ "in" +roomNumber;
			System.out.println(hotelInfo);                                                                                                                                   //45
		String notificationMessage = "You have 3 new messages.";
			System.out.println("Message format like this-"+notificationMessage);
		String logFilePath = "/logs/application.log";	
			System.out.println("file path is"+logFilePath);
		String backupFilePath = "/backups/dataBackup.zip";	
			System.out.println("backup file psth is:"+backupFilePath);                                                                                                                                   //46
		String contactNo="8767653129";	
			System.out.println(contactNo);
		String favoriteBook = "1984";	
			System.out.println(favoriteBook);
		String maritalStatus="Single";	
			System.out.println("marital Status is:"+maritalStatus);                                                                                                                                   //47
		String gender="Female"; 	
			System.out.println("Gender is"+gender);
		String securityCode="123abcd";	
			System.out.println("security code is:"+securityCode);
		String phoneLock="phone can be unocked using this "+securityCode+"by entering in phone"; 	
			System.out.println(phoneLock);                                                                                                                              											     //48
		String populationOfIndia="1.44 Million";	
			System.out.println("the population of India:"+populationOfIndia);
		String incrementInPopulation= "Every 10 mins the 100 to 200 count will increase in population so"+populationOfIndia + "is just appr. number";	
			System.out.println(incrementInPopulation);
		String speciesOfPlants="8.1 billion";	
			System.out.println("There are"+speciesOfPlants+"plant population in the world");
		String animalSpecies="There are 2 millions of animals are there";
		String totalNumbers="There are"+speciesOfPlants+"species of plant and "+animalSpecies+"of animal species are there in the world";
			System.out.println(totalNumbers);
		String vowelsInAlph="aeiou";
			System.out.println("there are 5 vowels in english alphabet:"+vowelsInAlph);
		String addtnlVowelInAlph = vowelsInAlph+"and h is also considered as vowel in earlier";
			System.out.println("description about vowels:"+addtnlVowelInAlph);
		String consonentsInAplh="bcdfghjklmnpqrstvwxyz";		
			System.out.println("There are 21 consonents in english alphabet:"+consonentsInAplh);
		String passKey="security code:"+securityCode;
			System.out.println(passKey);
		String messageQuotedByCustomer="customer instruction:"+deliveryInstructions;
			System.out.println(messageQuotedByCustomer);
		String transactionStatus="payment status:"+paymentStatus;
			System.out.println(transactionStatus);
		String nameOfWonder="egypt pyramid";
			System.out.println(nameOfWonder);
		String countryOfOrigin="Egypt";
			System.out.println(countryOfOrigin);
		String wonderDetails=nameOfWonder+" is One of the seven wonder"+"in"+countryOfOrigin;
			System.out.println(wonderDetails);
			

	}
}

